#!/bin/bash
#
# smpirun - share resource for mpirun
#
# shellcheck disable=SC2046
#

# Don't continue for any errors nor with undefined variables
set -euo pipefail
thiscommand="$0"

report() {
    local toscreen="$1"
    local exitonerror="$2"
    local exitcode="$3"
    local message="$4"
    local logfile="${5:-}"
    local logtime="${6:-}"
    local fullmessage=""
    local prefixmessage="INFO "
    if [ "${exitcode}" != 0 ]; then
        prefixmessage="ERROR"
    fi
    fullmessage="${prefixmessage} (${thiscommand}): ${message}"
    if $toscreen; then
        echo "${fullmessage}" 1>&2
    fi
    if [ -n "${logfile}" ]; then
        if [ -z "${logtime}" ]; then
            logtime=$(/usr/bin/date +"%Y-%m-%d@%H:%M:%S")
        fi
        echo "${logtime}: ${fullmessage}" >> "${logfile}"
    fi
    if "${exitonerror}"; then
        if [ "${exitcode}" != 0 ]; then
            exit "${exitcode}"
        fi
    fi
}

# 0. Check if mpirun is a known command and works

if ! /usr/bin/which mpirun >&/dev/null
then
    report true true 1 "Command 'mpirun' not found."
fi
if ! mpirun -n 1 hostname >&/dev/null
then
    report true true 1 "Command 'mpirun' is not functional."
fi

# 1. Setup hostfile.

# 1a) Determine a (hopefully) unique name for the HOSTFILE.
if [ -d "${SCRATCH:-}" ] && [ -n "${SLURM_JOBID:-}" ]
then
    HOSTFILE="${SCRATCH}/.mresource/hostfile-${SLURM_JOBID}.txt"
elif [ -d "/scratch/${USER}" ] && [ -n "${SLURM_JOBID:-}" ]
then
    HOSTFILE="/scratch/${USER}/.mresource/hostfile-${SLURM_JOBID}.txt"
else
    HOSTFILE="/tmp/hostfile.txt"
fi

# 1b) Check existing HOSTFILE.
MUSTGENERATEHOSTFILE=false
if ! [ -f "${HOSTFILE}" ]
then
    HOSTFILEDIR=$(/usr/bin/dirname "${HOSTFILE}")    
    MUSTGENERATEHOSTFILE=true
    if ! /usr/bin/mkdir -p "${HOSTFILEDIR}"
    then
        report true true 1 "Could not create directory '${HOSTFILEDIR}'"
    fi
else
    nslots=$(mpirun hostname | wc -l)
    nslotsinfile=$(/usr/bin/cat "${HOSTFILE}" | /usr/bin/wc -l)    
    if [ "${nslots}" != "${nslotsinfile}" ]
    then
        nslotsinuse=$(/usr/bin/cat "${HOSTFILE}" | /usr/bin/grep "^!" | /usr/bin/wc -l)
        if (( nslotsinuse > 0 ))
        then
            report true true 1 "Discrepency in number of slots in file '${HOSTFILE}'"
        else
            MUSTGENERATEHOSTFILE=true
        fi
    fi
fi

# 1c) Create the HOSTFILE if necessary.
if ${MUSTGENERATEHOSTFILE}
then
    if ! mresource create -f "${HOSTFILE}" $(mpirun hostname)
    then
        \rm -f "${HOSTFILE}"
        report true true 1 "Could not successfully create file '${HOSTFILE}'"
    fi
    createtimestamp=$(/usr/bin/date +"%Y-%m-%d@%H:%M:%S")
    echo "# This is the log file '$(basename "${HOSTFILE}.log")', created in the directory '$(dirname "${HOSTFILE}")' on ${createtimestamp}." > "${HOSTFILE}.log"
    report true false 0 "Created hostfile '$(basename "${HOSTFILE}")' in the directory '$(dirname "${HOSTFILE}")'." "${HOSTFILE}.log" "${createtimestamp}"
    report true false 0 "Logs are written to '$(basename "${HOSTFILE}.log")' in the same directory." "${HOSTFILE}.log" "${createtimestamp}"
else
    report true false 0 "See '${HOSTFILE}.log' for logging messages."
fi


# 2. Pick out the number of processes N from the arguments.

# 2a) Search through arguments for -n,-c,-np, or --n.
previousarg=""
N=0
for arg in "$@"
do
    case "${previousarg}" in
        -n|-c|-np|--n)
            if ! (( N="${arg}" ))
            then
                report true true 1 "${arg} is not a number"
            fi
            break
    esac
    previousarg="${arg}"
done

# 2b) If no -n, --n, -c, or --np argument was given, use all available slots. 
if [ "${N}" = 0 ]
then
    N=$(/usr/bin/cat "${HOSTFILE}" | /usr/bin/grep -v "^!" | /usr/bin/wc -l)
fi

# 3. Get resources from the HOSTFILE (5s timeout) and store in separate file.

FRACTIONALHOSTFILE=$(mktemp)
starttimestamp=$(/usr/bin/date +"%Y-%m-%d@%H:%M:%S")
error=0 # catching error code to be able to report failures
mresource get -f "${HOSTFILE}" -n "${N}" -t 5 > "${FRACTIONALHOSTFILE}" || error="$?"
if [ "$error" = 0 ]
then
    whichmpirun=$(/usr/bin/which mpirun)
    whichhosts=$(/usr/bin/cat "${FRACTIONALHOSTFILE}"|/usr/bin/tr '\n' ',')
    report false false 0 "${whichmpirun} --host ${whichhosts} $@" "${HOSTFILE}.log" "${starttimestamp}"
    nlines=$(cat "${HOSTFILE}.log" | wc -l)
    "${whichmpirun}" --host ${whichhosts} "$@" || error=$?
    # mpirun --hostfile "${FRACTIONALHOSTFILE}" "$@" || error=$?
    stoptimestamp=$(/usr/bin/date +"%Y-%m-%d@%H:%M:%S")
    report false false "${error}" "Command from line ${nlines} finished with exit code ${error}" "${HOSTFILE}.log" "${stoptimestamp}"
else
    case "${error}" in
        1) errortype="File could not be opened" ;;
        2) errortype="File could not be found" ;;
        3) errortype="Incorrect mresource arguments" ;;
        4) errortype="Time-out" ;;
        *) errortype="Unknown error" ;;
    esac
    report true false "${error}" "Could not get ${N} resources from '${HOSTFILE}' (${errortype})." "${HOSTFILE}.log" "${starttimestamp}"
fi

mresource put -f "${HOSTFILE}" $(cat "${FRACTIONALHOSTFILE}")
\rm -f  "${FRACTIONALHOSTFILE}"
exit "${error}"
